version: '2.0'
services:
  web:
    env_file:
     - ./production.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:8000"
    links:
    - db
  db:
    environment:
      - MONGO_INITDB_DATABASE=climate
    build:
      context: .
      dockerfile: mongo.dock
volumes:
  logvolume01: {}
